# Generated by Django 3.1.4 on 2020-12-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budgets', '0004_auto_20201223_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glavbudgetclass',
            options={'verbose_name': 'Публично-правовые образования', 'verbose_name_plural': 'Справочники ППО по бюджетной классификации'},
        ),
    ]
