# Generated by Django 3.1.4 on 2020-12-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budgets', '0005_auto_20201224_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glavbudgetclass',
            options={'verbose_name': 'Публично-правовые образования', 'verbose_name_plural': 'Справочник ППО по бюджетной классификации'},
        ),
    ]
