# Generated by Django 3.1.4 on 2020-12-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budgets', '0006_auto_20201224_0958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlavBudgetClass',
            new_name='PPO_Budget',
        ),
    ]
